FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src


COPY ["CoursesApi.csproj", "./"]
RUN dotnet restore "CoursesApi.csproj"


COPY . .
RUN dotnet publish "CoursesApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8081

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CoursesApi.dll"]